---
- name: Setup new project infrastructure
  hosts: all
  become: true
  gather_facts: false
  vars_prompt:
    - name: project_name
      prompt: "Enter the new project name"
      private: no

    - name: edge_ips
      prompt: "Enter the list of IPs for edge servers (comma-separated) or the number of containers to use"
      private: no

    - name: staging_ips
      prompt: "Enter the list of IPs for staging servers (comma-separated) or the number of containers to use"
      private: no

  tasks:
    - name: Convert edge IPs/count to a list
      set_fact:
        edge_ip_list: "{{ edge_ips.split(',') if edge_ips | regex_search('^(\\d{1,3}\\.){3}\\d{1,3}(,\\s*(\\d{1,3}\\.){3}\\d{1,3})*$') else range(1, edge_ips | int + 1) | map('regex_replace', '^', 'edge-0') | map('regex_replace', '$', '.' + project_name + '.my.home') | list }}"
      when: edge_ips != ''

    - name: Convert staging IPs/count to a list
      set_fact:
        staging_ip_list: "{{ staging_ips.split(',') if staging_ips | regex_search('^(\\d{1,3}\\.){3}\\d{1,3}(,\\s*(\\d{1,3}\\.){3}\\d{1,3})*$') else range(1, staging_ips | int + 1) | map('regex_replace', '^', 'staging-0') | map('regex_replace', '$', '.' + project_name + '.my.home') | list }}"
      when: staging_ips != ''

    - name: Setup edge servers
      include_role:
        name: infrastructure
        tasks_from: web.yml
      vars:
        project_name: "{{ item }}"
      loop: "{{ edge_ip_list }}"
      loop_control:
        loop_var: project_name

    - name: Setup staging servers
      include_role:
        name: infrastructure
        tasks_from: web.yml
      vars:
        project_name: "{{ item }}"
      loop: "{{ staging_ip_list }}"
      loop_control:
        loop_var: project_name
